import type { Template } from "@/lib/types";

const EVERYDAY = [0, 1, 2, 3, 4, 5, 6];
const WEEKDAYS = [1, 2, 3, 4, 5];

export const TEMPLATES: Template[] = [
  {
    id: "morning",
    name: "Morning Routine",
    emoji: "☀️",
    blurb: "Water, make the bed, stretch, and start the day on rails.",
    category: "morning",
    startTime: "06:30",
    days: EVERYDAY,
    steps: [
      { title: "Drink water", emoji: "💧", durationSec: 60 },
      { title: "Make the bed", emoji: "🛏️", durationSec: 120 },
      { title: "Open the blinds", emoji: "🪟", durationSec: 60 },
      { title: "Stretch", emoji: "🧘", durationSec: 300 },
      { title: "Shower", emoji: "🚿", durationSec: 600 },
      { title: "Get dressed", emoji: "👕", durationSec: 300 },
      { title: "Breakfast", emoji: "🥣", durationSec: 900 },
      { title: "Plan the day", emoji: "📝", durationSec: 300 },
    ],
  },
  {
    id: "night",
    name: "Night Wind-Down",
    emoji: "🌙",
    blurb: "ADHD-friendly evening reset that actually ends the day.",
    category: "night",
    startTime: "21:30",
    days: EVERYDAY,
    steps: [
      { title: "Tidy one surface", emoji: "🧹", durationSec: 180 },
      { title: "Phone on charger", emoji: "📵", durationSec: 120 },
      { title: "Skincare", emoji: "🧴", durationSec: 480 },
      { title: "Journal three lines", emoji: "📓", durationSec: 300 },
      { title: "Tomorrow's top 3", emoji: "✅", durationSec: 180 },
      { title: "Read", emoji: "📖", durationSec: 600 },
      { title: "Lights out breath", emoji: "🕯️", durationSec: 120 },
    ],
  },
  {
    id: "pomo",
    name: "Focus Pomodoro",
    emoji: "🍅",
    blurb: "Four deep-work blocks with short breaks. Press start, stay in it.",
    category: "focus",
    startTime: "09:00",
    anytime: true,
    days: WEEKDAYS,
    steps: [
      { title: "Focus", emoji: "🎯", durationSec: 1500 },
      { title: "Short break", emoji: "☕", durationSec: 300 },
      { title: "Focus", emoji: "🎯", durationSec: 1500 },
      { title: "Short break", emoji: "🌿", durationSec: 300 },
      { title: "Focus", emoji: "🎯", durationSec: 1500 },
      { title: "Short break", emoji: "💧", durationSec: 300 },
      { title: "Focus", emoji: "🎯", durationSec: 1500 },
      { title: "Long break", emoji: "🚶", durationSec: 900 },
    ],
  },
  {
    id: "workout",
    name: "Workout",
    emoji: "💪",
    blurb: "Warm up, move, stretch. A complete session you can actually finish.",
    category: "body",
    startTime: "07:30",
    days: [1, 3, 5, 0],
    steps: [
      { title: "Warm up", emoji: "🔥", durationSec: 300 },
      { title: "Strength", emoji: "🏋️", durationSec: 1200 },
      { title: "Cardio burst", emoji: "🏃", durationSec: 600 },
      { title: "Stretch", emoji: "🤸", durationSec: 300 },
      { title: "Cool down", emoji: "😌", durationSec: 180 },
    ],
  },
  {
    id: "selfcare",
    name: "Self-Care Reset",
    emoji: "🌿",
    blurb: "Small, obvious next steps when the day feels too loud.",
    category: "adhd",
    startTime: "16:00",
    anytime: true,
    days: EVERYDAY,
    steps: [
      { title: "Drink water", emoji: "💧", durationSec: 60 },
      { title: "Step outside", emoji: "🌤️", durationSec: 180 },
      { title: "Body scan", emoji: "🫀", durationSec: 180 },
      { title: "One kind task", emoji: "💛", durationSec: 300 },
      { title: "Eat something real", emoji: "🍎", durationSec: 480 },
    ],
  },
  {
    id: "daily-reset",
    name: "Daily Reset",
    emoji: "🔄",
    blurb: "A 20-minute sweep so tomorrow-you walks into a clear room.",
    category: "reset",
    startTime: "20:00",
    days: EVERYDAY,
    steps: [
      { title: "Dishes", emoji: "🍽️", durationSec: 480 },
      { title: "Wipe counters", emoji: "✨", durationSec: 180 },
      { title: "Laundry in the hamper", emoji: "🧺", durationSec: 180 },
      { title: "Bag by the door", emoji: "🎒", durationSec: 120 },
      { title: "Tomorrow clothes", emoji: "👔", durationSec: 180 },
    ],
  },
  {
    id: "school",
    name: "School Day Launch",
    emoji: "🎒",
    blurb: "Get out the door without the scramble.",
    category: "morning",
    startTime: "06:45",
    days: WEEKDAYS,
    steps: [
      { title: "Wake + water", emoji: "💧", durationSec: 120 },
      { title: "Get dressed", emoji: "👕", durationSec: 360 },
      { title: "Pack bag", emoji: "🎒", durationSec: 300 },
      { title: "Breakfast", emoji: "🍞", durationSec: 720 },
      { title: "Teeth + face", emoji: "🪥", durationSec: 240 },
      { title: "Shoes and leave", emoji: "👟", durationSec: 180 },
    ],
  },
  {
    id: "work-prep",
    name: "Work Prep",
    emoji: "💻",
    blurb: "Close the gap between sitting down and actually starting.",
    category: "focus",
    startTime: "08:45",
    days: WEEKDAYS,
    steps: [
      { title: "Desk clear", emoji: "🗂️", durationSec: 180 },
      { title: "Open today's one thing", emoji: "📌", durationSec: 120 },
      { title: "Inbox triage", emoji: "✉️", durationSec: 300 },
      { title: "Calendar glance", emoji: "📅", durationSec: 120 },
      { title: "Deep work block", emoji: "🧠", durationSec: 1500 },
    ],
  },
  {
    id: "athlete-am",
    name: "Athlete Dawn",
    emoji: "🥇",
    blurb: "Inspired by 4 a.m. training blocks — early, simple, no debate.",
    category: "body",
    startTime: "04:30",
    days: [1, 2, 3, 4, 5],
    steps: [
      { title: "Out of bed", emoji: "⏰", durationSec: 60 },
      { title: "Water + salt", emoji: "💧", durationSec: 120 },
      { title: "Mobility", emoji: "🧘", durationSec: 600 },
      { title: "Training", emoji: "🏋️", durationSec: 2700 },
      { title: "Protein breakfast", emoji: "🍳", durationSec: 900 },
      { title: "Cold shower", emoji: "🧊", durationSec: 300 },
    ],
  },
  {
    id: "founder-am",
    name: "Maker Morning",
    emoji: "🚀",
    blurb: "Inspired by high-output mornings: journal, move, then make.",
    category: "morning",
    startTime: "05:30",
    days: EVERYDAY,
    steps: [
      { title: "Make the bed", emoji: "🛏️", durationSec: 120 },
      { title: "Journal", emoji: "✍️", durationSec: 600 },
      { title: "Meditation", emoji: "🧘", durationSec: 600 },
      { title: "Workout", emoji: "🏃", durationSec: 1800 },
      { title: "Cold water", emoji: "🚿", durationSec: 300 },
      { title: "Deep work", emoji: "💻", durationSec: 3600 },
    ],
  },
  {
    id: "miracle",
    name: "Quiet Morning",
    emoji: "🌅",
    blurb: "Silence, sweat, read, write — a classic six-part start.",
    category: "morning",
    startTime: "06:00",
    days: EVERYDAY,
    steps: [
      { title: "Silence", emoji: "🤫", durationSec: 600 },
      { title: "Affirmations", emoji: "💬", durationSec: 300 },
      { title: "Visualization", emoji: "🌈", durationSec: 300 },
      { title: "Exercise", emoji: "🏃", durationSec: 1200 },
      { title: "Read", emoji: "📚", durationSec: 1200 },
      { title: "Scribe", emoji: "✍️", durationSec: 600 },
    ],
  },
  {
    id: "adhd-start",
    name: "Just Start",
    emoji: "⚡",
    blurb: "Tiny first steps when starting is the whole problem.",
    category: "adhd",
    startTime: "09:00",
    anytime: true,
    days: EVERYDAY,
    steps: [
      { title: "Stand up", emoji: "🧍", durationSec: 30 },
      { title: "Drink water", emoji: "💧", durationSec: 45 },
      { title: "Put on shoes", emoji: "👟", durationSec: 60 },
      { title: "2-minute tidy", emoji: "🧹", durationSec: 120 },
      { title: "Open the task", emoji: "📂", durationSec: 60 },
      { title: "Work for 10", emoji: "⏱️", durationSec: 600 },
    ],
  },
  {
    id: "yoga",
    name: "Yoga Flow",
    emoji: "🧘",
    blurb: "A short mat session you can finish before breakfast.",
    category: "body",
    startTime: "07:00",
    days: EVERYDAY,
    steps: [
      { title: "Roll out the mat", emoji: "🧘", durationSec: 60 },
      { title: "Sun salutations", emoji: "🌅", durationSec: 480 },
      { title: "Standing poses", emoji: "🧍", durationSec: 360 },
      { title: "Floor stretch", emoji: "🤸", durationSec: 300 },
      { title: "Savasana", emoji: "😌", durationSec: 180 },
    ],
  },
];

export const EMOJI_SET = [
  "☀️",
  "🌙",
  "💧",
  "🛏️",
  "🧘",
  "🚿",
  "👕",
  "🥣",
  "📝",
  "🧹",
  "📵",
  "🧴",
  "📓",
  "✅",
  "📖",
  "🕯️",
  "🍅",
  "🎯",
  "☕",
  "💪",
  "🏋️",
  "🏃",
  "🤸",
  "🌿",
  "🔄",
  "🎒",
  "💻",
  "🧠",
  "🥇",
  "🚀",
  "🌅",
  "⚡",
  "🍎",
  "🪥",
  "👟",
  "✉️",
  "📅",
  "🔥",
  "🧊",
  "✍️",
  "📚",
  "💛",
  "🫀",
  "🌤️",
  "🍽️",
  "✨",
  "🧺",
  "👔",
  "🍞",
  "🥚",
  "🎧",
  "💊",
  "🐶",
  "🌱",
  "🎵",
  "🦷",
  "🧼",
  "🫖",
  "🪟",
];
