/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as RemindersRouteImport } from './routes/reminders'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as YouRouteImport } from './routes/you'
import { Route as RoutineIdRouteImport } from './routes/routine.$id'
import { Route as RunIdRouteImport } from './routes/run.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const RemindersRoute = RemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const YouRoute = YouRouteImport.update({
  id: '/you',
  path: '/you',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutineIdRoute = RoutineIdRouteImport.update({
  id: '/routine/$id',
  path: '/routine/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RunIdRoute = RunIdRouteImport.update({
  id: '/run/$id',
  path: '/run/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/reminders': typeof RemindersRoute
  '/stats': typeof StatsRoute
  '/you': typeof YouRoute
  '/routine/$id': typeof RoutineIdRoute
  '/run/$id': typeof RunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/reminders': typeof RemindersRoute
  '/stats': typeof StatsRoute
  '/you': typeof YouRoute
  '/routine/$id': typeof RoutineIdRoute
  '/run/$id': typeof RunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/reminders': typeof RemindersRoute
  '/stats': typeof StatsRoute
  '/you': typeof YouRoute
  '/routine/$id': typeof RoutineIdRoute
  '/run/$id': typeof RunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explore'
    | '/reminders'
    | '/stats'
    | '/you'
    | '/routine/$id'
    | '/run/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explore'
    | '/reminders'
    | '/stats'
    | '/you'
    | '/routine/$id'
    | '/run/$id'
  id:
    | '__root__'
    | '/'
    | '/explore'
    | '/reminders'
    | '/stats'
    | '/you'
    | '/routine/$id'
    | '/run/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExploreRoute: typeof ExploreRoute
  RemindersRoute: typeof RemindersRoute
  StatsRoute: typeof StatsRoute
  YouRoute: typeof YouRoute
  RoutineIdRoute: typeof RoutineIdRoute
  RunIdRoute: typeof RunIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminders': {
      id: '/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof RemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/you': {
      id: '/you'
      path: '/you'
      fullPath: '/you'
      preLoaderRoute: typeof YouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routine/$id': {
      id: '/routine/$id'
      path: '/routine/$id'
      fullPath: '/routine/$id'
      preLoaderRoute: typeof RoutineIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/run/$id': {
      id: '/run/$id'
      path: '/run/$id'
      fullPath: '/run/$id'
      preLoaderRoute: typeof RunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExploreRoute: ExploreRoute,
  RemindersRoute: RemindersRoute,
  StatsRoute: StatsRoute,
  YouRoute: YouRoute,
  RoutineIdRoute: RoutineIdRoute,
  RunIdRoute: RunIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
