/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgencyRouteImport } from './routes/agency'
import { Route as BrainRouteImport } from './routes/brain'
import { Route as CheckInRouteImport } from './routes/check-in'
import { Route as HabitsRouteImport } from './routes/habits'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as MoreRouteImport } from './routes/more'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as RoutinesRouteImport } from './routes/routines'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SkillRouteImport } from './routes/skill'
import { Route as StartRouteImport } from './routes/start'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as UnlearnRouteImport } from './routes/unlearn'
import { Route as WeekRouteImport } from './routes/week'
import { Route as RoutineIdRouteImport } from './routes/routine.$id'
import { Route as RunIdRouteImport } from './routes/run.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencyRoute = AgencyRouteImport.update({
  id: '/agency',
  path: '/agency',
  getParentRoute: () => rootRouteImport,
} as any)
const BrainRoute = BrainRouteImport.update({
  id: '/brain',
  path: '/brain',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckInRoute = CheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitsRoute = HabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutinesRoute = RoutinesRouteImport.update({
  id: '/routines',
  path: '/routines',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillRoute = SkillRouteImport.update({
  id: '/skill',
  path: '/skill',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const UnlearnRoute = UnlearnRouteImport.update({
  id: '/unlearn',
  path: '/unlearn',
  getParentRoute: () => rootRouteImport,
} as any)
const WeekRoute = WeekRouteImport.update({
  id: '/week',
  path: '/week',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutineIdRoute = RoutineIdRouteImport.update({
  id: '/routine/$id',
  path: '/routine/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RunIdRoute = RunIdRouteImport.update({
  id: '/run/$id',
  path: '/run/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agency': typeof AgencyRoute
  '/brain': typeof BrainRoute
  '/check-in': typeof CheckInRoute
  '/habits': typeof HabitsRoute
  '/journal': typeof JournalRoute
  '/learn': typeof LearnRoute
  '/more': typeof MoreRoute
  '/progress': typeof ProgressRoute
  '/routines': typeof RoutinesRoute
  '/settings': typeof SettingsRoute
  '/skill': typeof SkillRoute
  '/start': typeof StartRoute
  '/tasks': typeof TasksRoute
  '/unlearn': typeof UnlearnRoute
  '/week': typeof WeekRoute
  '/routine/$id': typeof RoutineIdRoute
  '/run/$id': typeof RunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agency': typeof AgencyRoute
  '/brain': typeof BrainRoute
  '/check-in': typeof CheckInRoute
  '/habits': typeof HabitsRoute
  '/journal': typeof JournalRoute
  '/learn': typeof LearnRoute
  '/more': typeof MoreRoute
  '/progress': typeof ProgressRoute
  '/routines': typeof RoutinesRoute
  '/settings': typeof SettingsRoute
  '/skill': typeof SkillRoute
  '/start': typeof StartRoute
  '/tasks': typeof TasksRoute
  '/unlearn': typeof UnlearnRoute
  '/week': typeof WeekRoute
  '/routine/$id': typeof RoutineIdRoute
  '/run/$id': typeof RunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agency': typeof AgencyRoute
  '/brain': typeof BrainRoute
  '/check-in': typeof CheckInRoute
  '/habits': typeof HabitsRoute
  '/journal': typeof JournalRoute
  '/learn': typeof LearnRoute
  '/more': typeof MoreRoute
  '/progress': typeof ProgressRoute
  '/routines': typeof RoutinesRoute
  '/settings': typeof SettingsRoute
  '/skill': typeof SkillRoute
  '/start': typeof StartRoute
  '/tasks': typeof TasksRoute
  '/unlearn': typeof UnlearnRoute
  '/week': typeof WeekRoute
  '/routine/$id': typeof RoutineIdRoute
  '/run/$id': typeof RunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agency'
    | '/brain'
    | '/check-in'
    | '/habits'
    | '/journal'
    | '/learn'
    | '/more'
    | '/progress'
    | '/routines'
    | '/settings'
    | '/skill'
    | '/start'
    | '/tasks'
    | '/unlearn'
    | '/week'
    | '/routine/$id'
    | '/run/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agency'
    | '/brain'
    | '/check-in'
    | '/habits'
    | '/journal'
    | '/learn'
    | '/more'
    | '/progress'
    | '/routines'
    | '/settings'
    | '/skill'
    | '/start'
    | '/tasks'
    | '/unlearn'
    | '/week'
    | '/routine/$id'
    | '/run/$id'
  id:
    | '__root__'
    | '/'
    | '/agency'
    | '/brain'
    | '/check-in'
    | '/habits'
    | '/journal'
    | '/learn'
    | '/more'
    | '/progress'
    | '/routines'
    | '/settings'
    | '/skill'
    | '/start'
    | '/tasks'
    | '/unlearn'
    | '/week'
    | '/routine/$id'
    | '/run/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgencyRoute: typeof AgencyRoute
  BrainRoute: typeof BrainRoute
  CheckInRoute: typeof CheckInRoute
  HabitsRoute: typeof HabitsRoute
  JournalRoute: typeof JournalRoute
  LearnRoute: typeof LearnRoute
  MoreRoute: typeof MoreRoute
  ProgressRoute: typeof ProgressRoute
  RoutinesRoute: typeof RoutinesRoute
  SettingsRoute: typeof SettingsRoute
  SkillRoute: typeof SkillRoute
  StartRoute: typeof StartRoute
  TasksRoute: typeof TasksRoute
  UnlearnRoute: typeof UnlearnRoute
  WeekRoute: typeof WeekRoute
  RoutineIdRoute: typeof RoutineIdRoute
  RunIdRoute: typeof RunIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agency': {
      id: '/agency'
      path: '/agency'
      fullPath: '/agency'
      preLoaderRoute: typeof AgencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brain': {
      id: '/brain'
      path: '/brain'
      fullPath: '/brain'
      preLoaderRoute: typeof BrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-in': {
      id: '/check-in'
      path: '/check-in'
      fullPath: '/check-in'
      preLoaderRoute: typeof CheckInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habits': {
      id: '/habits'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof HabitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routines': {
      id: '/routines'
      path: '/routines'
      fullPath: '/routines'
      preLoaderRoute: typeof RoutinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skill': {
      id: '/skill'
      path: '/skill'
      fullPath: '/skill'
      preLoaderRoute: typeof SkillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unlearn': {
      id: '/unlearn'
      path: '/unlearn'
      fullPath: '/unlearn'
      preLoaderRoute: typeof UnlearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/week': {
      id: '/week'
      path: '/week'
      fullPath: '/week'
      preLoaderRoute: typeof WeekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routine/$id': {
      id: '/routine/$id'
      path: '/routine/$id'
      fullPath: '/routine/$id'
      preLoaderRoute: typeof RoutineIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/run/$id': {
      id: '/run/$id'
      path: '/run/$id'
      fullPath: '/run/$id'
      preLoaderRoute: typeof RunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgencyRoute: AgencyRoute,
  BrainRoute: BrainRoute,
  CheckInRoute: CheckInRoute,
  HabitsRoute: HabitsRoute,
  JournalRoute: JournalRoute,
  LearnRoute: LearnRoute,
  MoreRoute: MoreRoute,
  ProgressRoute: ProgressRoute,
  RoutinesRoute: RoutinesRoute,
  SettingsRoute: SettingsRoute,
  SkillRoute: SkillRoute,
  StartRoute: StartRoute,
  TasksRoute: TasksRoute,
  UnlearnRoute: UnlearnRoute,
  WeekRoute: WeekRoute,
  RoutineIdRoute: RoutineIdRoute,
  RunIdRoute: RunIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
